import{useCallback,useEffect,useRef,useState}from'react';import type{AppStrings}from'../i18n';import type{GroupProgress,GroupResult,createGroupPlayBootstrapCoordinator}from'../group/groupPlayClient';
type Coordinator=ReturnType<typeof createGroupPlayBootstrapCoordinator>;const POLL_MS=5000;
export function GroupCompletionWaiting({groupId,coordinator,t,onResult,initialClosed=false}:{groupId:string;coordinator:Coordinator;t:AppStrings;onResult:(result:GroupResult)=>void;initialClosed?:boolean}){const[progress,setProgress]=useState<GroupProgress|null>(null),[error,setError]=useState(false),[resultPending,setResultPending]=useState(initialClosed);const mounted=useRef(false),inFlight=useRef(false),resultInFlight=useRef(false)
 const loadResult=useCallback(async()=>{if(resultInFlight.current)return;resultInFlight.current=true;try{const result=await coordinator.getResult(groupId);if(mounted.current){setError(false);onResult(result)}}catch{if(mounted.current)setError(true)}finally{resultInFlight.current=false;if(mounted.current)setResultPending(false)}},[coordinator,groupId,onResult])
 const refresh=useCallback(async()=>{if(inFlight.current||initialClosed)return;inFlight.current=true;try{const next=await coordinator.getProgress(groupId);if(mounted.current){setProgress(next);setError(false)}}catch{if(mounted.current)setError(true)}finally{inFlight.current=false}},[coordinator,groupId,initialClosed])
 useEffect(()=>{mounted.current=true;const timer=initialClosed?window.setTimeout(()=>{void loadResult()},0):null;return()=>{mounted.current=false;if(timer!==null)window.clearTimeout(timer)}},[initialClosed,loadResult])
 useEffect(()=>{if(progress?.status!=='closed')return;const timer=window.setTimeout(()=>{void loadResult()},0);return()=>window.clearTimeout(timer)},[progress?.status,loadResult])
 useEffect(()=>{if(initialClosed||progress?.status==='closed')return;const tick=()=>{if(document.visibilityState==='visible')void refresh()};const initial=window.setTimeout(tick,0),timer=window.setInterval(tick,POLL_MS);document.addEventListener('visibilitychange',tick);return()=>{window.clearTimeout(initial);window.clearInterval(timer);document.removeEventListener('visibilitychange',tick)}},[refresh,progress?.status,initialClosed])
 const close=useCallback(async()=>{if(!progress?.hostCloseAvailable||!coordinator.hasHostCapability(groupId)||resultPending)return;if(!window.confirm(t.groupCloseConfirm))return;setResultPending(true);try{const closed=await coordinator.closeGroup(groupId);setProgress(closed);setError(false)}catch{setError(true);setResultPending(false)}},[progress,coordinator,groupId,resultPending,t.groupCloseConfirm])
 const retry=useCallback(()=>{setError(false);if(initialClosed||progress?.status==='closed'){setResultPending(true);void loadResult()}else void refresh()},[initialClosed,progress?.status,loadResult,refresh])
 return <div className="duel-play-status" aria-live="polite"><p>{initialClosed||progress?.status==='closed'||resultPending?t.groupResultLoading:t.groupPlayComplete}</p>{progress?.status==='open'?<><p>{t.groupParticipantsProgress(progress.acceptedCount,progress.playerLimit)}</p><p>{t.groupCompletedProgress(progress.completedCount,progress.playerLimit)}</p></>:null}{progress?.hostCloseAvailable&&coordinator.hasHostCapability(groupId)?<button type="button" className="duel-btn duel-btn--primary" disabled={resultPending} onClick={()=>{void close()}}>{t.groupClose}</button>:null}{error?<><p className="duel-play-error" role="alert">{initialClosed||progress?.status==='closed'?t.groupResultError:t.groupProgressError}</p><button type="button" className="duel-btn" onClick={retry}>{t.groupResultRetry}</button></>:null}</div>}
