/** GROUP progress, automatic finalize, host close, privacy, and waiting UI. */
import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{resolve}from'node:path';import{createGroupProgressHandler}from'../api/_group/matches/[groupId]/progress.ts';import{createGroupCloseHandler}from'../api/_group/matches/[groupId]/close.ts';import{GroupProgressError}from'../server/group/progress.ts';import{parseGroupProgress}from'../src/group/groupPlayClient.ts';
const root=resolve(import.meta.dirname,'..'),groupId='123e4567-e89b-42d3-a456-426614174000',requestId='423e4567-e89b-42d3-a456-426614174000';const view={groupId,playerLimit:4,acceptedCount:3,completedCount:2,status:'open' as const,selfCompleted:true,selfIsHostParticipant:true,hostCloseAvailable:true};
assert.deepEqual(parseGroupProgress(view,groupId),view);assert.throws(()=>parseGroupProgress({...view,participants:[{nickname:'secret'}]},groupId));assert.throws(()=>parseGroupProgress({...view,completedCount:4},groupId));
const progress=await createGroupProgressHandler(async()=>view)(new Request(`https://example.test/api/group/matches/${groupId}/progress`,{headers:{Authorization:'Bearer hidden'}}));assert.equal(progress.status,200);assert.equal(progress.headers.get('cache-control'),'no-store');const text=await progress.text();for(const secret of['nickname','participantId','score','roundNumber'])assert.equal(text.includes(secret),false)
const closed={...view,status:'closed' as const,hostCloseAvailable:false};const close=await createGroupCloseHandler(async()=>closed)(new Request(`https://example.test/api/group/matches/${groupId}/close`,{method:'POST',headers:{Authorization:'Bearer host','Idempotency-Key':requestId}}));assert.equal(close.status,200);assert.deepEqual(await close.json(),closed)
const denied=await createGroupCloseHandler(async()=>{throw new GroupProgressError('CONFLICT')})(new Request(`https://example.test/api/group/matches/${groupId}/close`,{method:'POST'}));assert.equal(denied.status,409)
const db=readFileSync(resolve(root,'server/db/groupProgress.ts'),'utf8');for(const part of['match.host_participant_id=self.id','count(other.id) filter','host.completed_at','for update of match',"status='closed'",'participant.completed_at is null','excluded_at=statement_timestamp()'])assert.ok(db.includes(part),part)
for(const file of['server/db/openGroupBag.ts','server/db/cashOutGroupRound.ts']){const source=readFileSync(resolve(root,file),'utf8');for(const part of['auto_closed','match.accepted_count=match.player_limit','completed_participant',"set status='closed'"])assert.ok(source.includes(part),`${file}: ${part}`)}
const resume=readFileSync(resolve(root,'server/db/groupPlay.ts'),'utf8');for(const part of["status = 'interrupted'",'completed_participant','auto_closed','for update of match, participant'])assert.ok(resume.includes(part),part)
const waiting=readFileSync(resolve(root,'src/components/GroupCompletionWaiting.tsx'),'utf8');for(const part of['POLL_MS = 5000','visibilityState','visibilitychange','groupPlayComplete','groupParticipantsProgress','groupCompletedProgress','groupCloseConfirm','hasHostCapability'])assert.ok(waiting.includes(part),part)
assert.equal(waiting.includes('displayNickname'),false);assert.equal(waiting.includes('participantId'),false)
console.log('verify:group-progress OK')
